### PR TITLE
MapInterface: Fix undefined behavior when using memcpy

### LINKED ISSUE #66: Joining game leads to stack-buffer-overflow
I recompiled 0.9.0-RC6 with [`-fsanitize=address,undefined`](https://github.com/google/sanitizers/wiki/AddressSanitizerFlags)

After clicking "play" to join a game, I got the output:

```
rendering text Please wait... generating palettes
2024-01-07 11:55:32 Server IP received: [69.164.193.165:3031]
2024-01-07 11:55:32 Querying server [69.164.193.165:3031]
2024-01-07 11:55:32 Server IP received: [200.7.8.112:3031]
2024-01-07 11:55:32 Querying server [200.7.8.112:3031]
2024-01-07 11:55:32 Server IP received: [168.138.227.180:3031]
2024-01-07 11:55:32 Querying server [168.138.227.180:3031]
2024-01-07 11:55:32 Server IP received: [168.75.93.220:3031]
2024-01-07 11:55:32 Querying server [168.75.93.220:3031]
2024-01-07 11:55:32 Server IP received: [129.148.47.197:3031]
2024-01-07 11:55:32 Querying server [129.148.47.197:3031]
2024-01-07 11:55:32 Server IP received: [144.22.134.200:3031]
2024-01-07 11:55:32 Querying server [144.22.134.200:3031]
2024-01-07 11:55:33 Stopping queries to servers, no more servers
=================================================================
==24703==ERROR: AddressSanitizer: stack-buffer-overflow on address 0x7f1bbdf4d200 at pc 0x7f1bc0971003 bp 0x7fff75db4f10 sp 0x7fff75db46b8
READ of size 23 at 0x7f1bbdf4d200 thread T0
    #0 0x7f1bc0971002 in __interceptor_memcpy /usr/src/debug/gcc/gcc/libsanitizer/sanitizer_common/sanitizer_common_interceptors.inc:899
    #1 0x558371cc9f69 in MapInterface::startMapLoad(char const*, char const*, bool, unsigned long) (/home/andy/src/netpanzer/netpanzer-0.9.0-RC-6/netpanzer+0x10d0f69) (BuildId: 178ad7a81f83f5cdda90544113090cf53b08f21c)
    #2 0x558371ce6031 in GameManager::startGameMapLoad(char const*, char const*, unsigned long) (/home/andy/src/netpanzer/netpanzer-0.9.0-RC-6/netpanzer+0x10ed031) (BuildId: 178ad7a81f83f5cdda90544113090cf53b08f21c)
    #3 0x558371cedfba in GameManager::startClientGameSetup(NetMessage const*, int*) (/home/andy/src/netpanzer/netpanzer-0.9.0-RC-6/netpanzer+0x10f4fba) (BuildId: 178ad7a81f83f5cdda90544113090cf53b08f21c)
    #4 0x558371c15119 in ClientConnectDaemon::connectFsm(NetMessage const*) (/home/andy/src/netpanzer/netpanzer-0.9.0-RC-6/netpanzer+0x101c119) (BuildId: 178ad7a81f83f5cdda90544113090cf53b08f21c)
    #5 0x558371c3ad97 in ClientMessageRouter::routeMessage(NetPacket const*) (/home/andy/src/netpanzer/netpanzer-0.9.0-RC-6/netpanzer+0x1041d97) (BuildId: 178ad7a81f83f5cdda90544113090cf53b08f21c)
    #6 0x558371c3b4d3 in ClientMessageRouter::routeMessages() (/home/andy/src/netpanzer/netpanzer-0.9.0-RC-6/netpanzer+0x10424d3) (BuildId: 178ad7a81f83f5cdda90544113090cf53b08f21c)
    #7 0x558371d767dc in BaseGameManager::simLoop() (/home/andy/src/netpanzer/netpanzer-0.9.0-RC-6/netpanzer+0x117d7dc) (BuildId: 178ad7a81f83f5cdda90544113090cf53b08f21c)
    #8 0x558371d74f33 in BaseGameManager::mainLoop() (/home/andy/src/netpanzer/netpanzer-0.9.0-RC-6/netpanzer+0x117bf33) (BuildId: 178ad7a81f83f5cdda90544113090cf53b08f21c)
    #9 0x558371d69822 in PlayerGameManager::mainLoop() (/home/andy/src/netpanzer/netpanzer-0.9.0-RC-6/netpanzer+0x1170822) (BuildId: 178ad7a81f83f5cdda90544113090cf53b08f21c)
    #10 0x558371c6d746 in netpanzer_main(int, char**) (/home/andy/src/netpanzer/netpanzer-0.9.0-RC-6/netpanzer+0x1074746) (BuildId: 178ad7a81f83f5cdda90544113090cf53b08f21c)
    #11 0x7f1bbfa6eccf  (/usr/lib/libc.so.6+0x27ccf) (BuildId: 8bfe03f6bf9b6a6e2591babd0bbc266837d8f658)
    #12 0x7f1bbfa6ed89 in __libc_start_main (/usr/lib/libc.so.6+0x27d89) (BuildId: 8bfe03f6bf9b6a6e2591babd0bbc266837d8f658)
    #13 0x558371b35314 in _start (/home/andy/src/netpanzer/netpanzer-0.9.0-RC-6/netpanzer+0xf3c314) (BuildId: 178ad7a81f83f5cdda90544113090cf53b08f21c)

Address 0x7f1bbdf4d200 is located in stack of thread T0 at offset 512 in frame
    #0 0x558371cc9b4f in MapInterface::startMapLoad(char const*, char const*, bool, unsigned long) (/home/andy/src/netpanzer/netpanzer-0.9.0-RC-6/netpanzer+0x10d0b4f) (BuildId: 178ad7a81f83f5cdda90544113090cf53b08f21c)

  This frame has 34 object(s):
    [48, 49) '<unknown>'
    [64, 65) '<unknown>'
    [80, 81) '<unknown>'
    [96, 97) '<unknown>'
    [112, 113) '<unknown>'
    [128, 129) '<unknown>'
    [144, 145) '<unknown>'
    [160, 161) '<unknown>'
    [176, 177) '<unknown>'
    [192, 193) '<unknown>'
    [208, 209) '<unknown>'
    [224, 225) '<unknown>'
    [240, 241) '<unknown>'
    [256, 257) '<unknown>'
    [272, 273) '<unknown>'
    [288, 289) '<unknown>'
    [304, 305) '<unknown>'
    [320, 321) '<unknown>'
    [336, 337) '<unknown>'
    [352, 384) '<unknown>'
    [416, 448) 'stpath' (line 55)
    [480, 512) 'tsname' (line 56) <== Memory access at offset 512 overflows this variable
    [544, 576) 'tsnamesub' (line 64)
    [608, 640) 'basepath' (line 66)
    [672, 704) '<unknown>'
    [736, 768) '<unknown>'
    [800, 832) 'cfgnamepath' (line 69)
    [864, 896) '<unknown>'
    [928, 960) '<unknown>'
    [992, 1024) '<unknown>'
    [1056, 1088) '<unknown>'
    [1120, 1144) 'subbuff' (line 58)
    [1184, 1440) 'path' (line 45)
    [1504, 1760) 'tile_set_path' (line 46)
HINT: this may be a false positive if your program uses some custom stack unwind mechanism, swapcontext or vfork
      (longjmp and C++ exceptions *are* supported)
SUMMARY: AddressSanitizer: stack-buffer-overflow /usr/src/debug/gcc/gcc/libsanitizer/sanitizer_common/sanitizer_common_interceptors.inc:899 in __interceptor_memcpy
Shadow bytes around the buggy address:
  0x7f1bbdf4cf80: 00 00 00 00 f3 f3 f3 f3 00 00 00 00 00 00 00 00
  0x7f1bbdf4d000: f1 f1 f1 f1 f1 f1 f8 f2 f8 f2 f8 f2 01 f2 01 f2
  0x7f1bbdf4d080: 01 f2 01 f2 01 f2 01 f2 01 f2 01 f2 01 f2 01 f2
  0x7f1bbdf4d100: 01 f2 01 f2 01 f2 01 f2 01 f2 01 f2 f8 f8 f8 f8
  0x7f1bbdf4d180: f2 f2 f2 f2 00 00 00 00 f2 f2 f2 f2 00 00 00 00
=>0x7f1bbdf4d200:[f2]f2 f2 f2 00 00 00 00 f2 f2 f2 f2 00 00 00 00
  0x7f1bbdf4d280: f2 f2 f2 f2 00 00 00 00 f2 f2 f2 f2 00 00 00 00
  0x7f1bbdf4d300: f2 f2 f2 f2 00 00 00 00 f2 f2 f2 f2 00 00 00 00
  0x7f1bbdf4d380: f2 f2 f2 f2 00 00 00 00 f2 f2 f2 f2 00 00 00 00
  0x7f1bbdf4d400: f2 f2 f2 f2 00 00 00 00 f2 f2 f2 f2 00 00 00 f2
  0x7f1bbdf4d480: f2 f2 f2 f2 00 00 00 00 00 00 00 00 00 00 00 00
Shadow byte legend (one shadow byte represents 8 application bytes):
  Addressable:           00
  Partially addressable: 01 02 03 04 05 06 07 
  Heap left redzone:       fa
  Freed heap region:       fd
  Stack left redzone:      f1
  Stack mid redzone:       f2
  Stack right redzone:     f3
  Stack after return:      f5
  Stack use after scope:   f8
  Global redzone:          f9
  Global init order:       f6
  Poisoned by user:        f7
  Container overflow:      fc
  Array cookie:            ac
  Intra object redzone:    bb
  ASan internal:           fe
  Left alloca redzone:     ca
  Right alloca redzone:    cb
==24703==ABORTING
```

### PR DESCRIPTION
**Pull request by andy5995**
fixes #66

### CODE REVIEW

File: src/NetPanzer/Interfaces/MapInterface.cpp [hunk 1]
```diff
@@ -55,11 +55,11 @@ bool MapInterface::startMapLoad( const char *file_path, const char *mapstyle_mpa
...
 
-    char subbuff[24];
-    memcpy( subbuff, &tsname[0], 23); // max 23 chars for tileset name
-    char * pch;
-    pch = strstr (subbuff,".tls");
-    strncpy (pch,"\0",1);
+    const int max_len_tsname = 23;
+    std::string subbuff = tsname.substr(0, max_len_tsname);
+    size_t found = subbuff.find(".tls");
+    if (found <= max_len_tsname)
```
Comment (winrid) [inline src/NetPanzer/Interfaces/MapInterface.cpp:61]: hm, find returns -1 when no match, but i guess since it's size_t it "overflows" to largest value of size_t and so this condition is false?

**Review by winrid — APPROVED** [review]

File: src/NetPanzer/Interfaces/MapInterface.cpp (hunk 1 above)
Comment (andy5995) [reply src/NetPanzer/Interfaces/MapInterface.cpp:61]: I'm not completely confident there.

https://cplusplus.com/reference/string/string/find/

>If no matches were found, the function returns [string::npos](https://cplusplus.com/string::npos).

If I interpret that right, it would return a very large value if the substring isn't found.

Comment (winrid) [reply src/NetPanzer/Interfaces/MapInterface.cpp:61]: in practice - yes - not saying there is an issue. just learning :)

Comment (andy5995) [reply src/NetPanzer/Interfaces/MapInterface.cpp:61]: Me too. I'm glad you questioned it. Feel free to do so any time you're not sure.

This is a bit ridiculous though: I tested and printed the return value of 'found' to stderr. Showed '-1'. 

So I changed the code and got this warning

```
../src/NetPanzer/Interfaces/MapInterface.cpp:61:15: warning: comparison of integer expressions of different signedness: ‘size_t’ {aka ‘long unsigned int’} and ‘int’ [-Wsign-compare]
   61 |     if (found != -1)
```
So even though I declared 'found' as a size_t, it returned a signed int, which should be unsigned (where ssize_t can be signed). As far as I know. ;)

File: src/NetPanzer/Interfaces/MapInterface.cpp [hunk 2]
```diff
@@ -55,11 +55,11 @@ bool MapInterface::startMapLoad( const char *file_path, const char *mapstyle_mpa
...
 
-    char subbuff[24];
-    memcpy( subbuff, &tsname[0], 23); // max 23 chars for tileset name
-    char * pch;
-    pch = strstr (subbuff,".tls");
-    strncpy (pch,"\0",1);
+    const int max_len_tsname = 23;
+    std::string subbuff = tsname.substr(0, max_len_tsname);
+    ssize_t found = subbuff.find(".tls");
+    if (found != -1)
```
Comment (winrid) [inline src/NetPanzer/Interfaces/MapInterface.cpp:61]: nit: maybe can compare against [string::npos](https://cplusplus.com/string::npos) directly

**Review by winrid — APPROVED** [review]

File: src/NetPanzer/Interfaces/MapInterface.cpp (hunk 2 above)
Comment (andy5995) [reply src/NetPanzer/Interfaces/MapInterface.cpp:61]: Looks like I should definitely do that https://stackoverflow.com/a/15740842

**Review by winrid — APPROVED** [review]
