### PR TITLE
fix some warnings (fixes #16)

### LINKED ISSUE #16: Fix Potential Overflows
```
src/NetPanzer/Views/Game/VehicleSelectionView.cpp: In static member function ‘static void VehicleSelectionView::drawMiniProductionStatus(Surface&)’:
src/NetPanzer/Views/Game/VehicleSelectionView.cpp:593:53: warning: ‘%s’ directive writing up to 255 bytes into a region of size 249 [-Wformat-overflow=]
  593 |                 sprintf(outpostUserNameBuf, "Owner: %s...", strBuf);
      |                                                     ^~      ~~~~~~
src/NetPanzer/Views/Game/VehicleSelectionView.cpp:593:24: note: ‘sprintf’ output between 11 and 266 bytes into a destination of size 256
  593 |                 sprintf(outpostUserNameBuf, "Owner: %s...", strBuf);
      |                 ~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
src/NetPanzer/Views/Game/VehicleSelectionView.cpp:611:40: warning: ‘...’ directive writing 3 bytes into a region of size between 1 and 256 [-Wformat-overflow=]
  611 |             sprintf(outpostNameBuf, "%s...",  strBuf);
      |                                        ^~~
src/NetPanzer/Views/Game/VehicleSelectionView.cpp:611:20: note: ‘sprintf’ output between 4 and 259 bytes into a destination of size 256
  611 |             sprintf(outpostNameBuf, "%s...",  strBuf);

```

### PR DESCRIPTION
**Pull request by andy5995**

### CODE REVIEW

**Comment by winrid** [comment]
yeah, we have a lot of signedness errors...

File: src/NetPanzer/Views/Game/VehicleSelectionView.cpp [hunk 1]
```diff
@@ -590,7 +591,7 @@ void VehicleSelectionView::drawMiniProductionStatus(Surface &dest)
             {
                 strncpy(strBuf, obj->occupying_player->getName().c_str() , 17);
                 strBuf[17] = 0; // fix runners
-                sprintf(outpostUserNameBuf, "Owner: %s...", strBuf);
+                sn_check(std::snprintf ( outpostUserNameBuf, sizeof outpostUserNameBuf, "Owner: %s...", strBuf ), sizeof outpostUserNameBuf );
```
Comment (andy5995) [inline src/NetPanzer/Views/Game/VehicleSelectionView.cpp:594]: The reason I don't call snprintf() from the macro is so that sn_check() can be used in other cases where one would want to just compare two values without using snprintf, which returns a value.

File: src/Lib/Util/StringUtil.hpp [hunk 2]
```diff
@@ -21,8 +21,14 @@ Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
 #include "Core/CoreTypes.hpp"
 #include <vector>
 
+#define sn_check(a, b) real_sn_check(a, b, __func__, __LINE__)
```
Comment (andy5995) [inline src/Lib/Util/StringUtil.hpp:24]: You want me to proceed fixing a few more warnings using this macro like I have it? Or something a little different? Any reason why we're not using Cpp string methods in place of sprintf?

Comment (winrid) [reply src/Lib/Util/StringUtil.hpp:24]: @andy5995 the ideal fix here is to just use cpp string stuff IMO.

Comment (andy5995) [reply src/Lib/Util/StringUtil.hpp]: ok, converted some things. On the right track now?

File: src/NetPanzer/Views/Game/VehicleSelectionView.cpp [hunk 3]
```diff
@@ -554,7 +554,7 @@ void VehicleSelectionView::drawMiniProductionStatus(Surface &dest)
 {
     char strBuf[256];
     char outpostNameBuf[256];
-    char outpostUserNameBuf[256];
+    std::string outpostUserNameBuf;
```
Comment (andy5995) [inline src/NetPanzer/Views/Game/VehicleSelectionView.cpp:557]: I hope this change won't slow things down too much. I'm not really knowledge about cpp automatic memory management related to strings.

File: src/NetPanzer/Views/Game/VehicleSelectionView.cpp [hunk 4]
```diff
@@ -590,11 +590,11 @@ void VehicleSelectionView::drawMiniProductionStatus(Surface &dest)
             {
                 strncpy(strBuf, obj->occupying_player->getName().c_str() , 17);
                 strBuf[17] = 0; // fix runners
-                sprintf(outpostUserNameBuf, "Owner: %s...", strBuf);
+                outpostUserNameBuf = std::string("Owner: ") + std::string(strBuf);
             }
             else
             {
-                sprintf(outpostUserNameBuf, "Owner: %s", obj->occupying_player->getName().c_str() );
+                outpostUserNameBuf = std::string("Ownder: ") + obj->occupying_player->getName();
```
Comment (winrid) [inline src/NetPanzer/Views/Game/VehicleSelectionView.cpp:597]: Typo in "Owner" here

File: src/NetPanzer/Views/Game/VehicleSelectionView.cpp (hunk 3 above)
Comment (winrid) [reply src/NetPanzer/Views/Game/VehicleSelectionView.cpp:557]: I think most of the time it will be stack allocated and less than the old size of 256 bytes anyway.

File: src/NetPanzer/Views/Game/VehicleSelectionView.cpp [hunk 5]
```diff
@@ -623,7 +623,7 @@ void VehicleSelectionView::drawMiniProductionStatus(Surface &dest)
                 // Objective is off.
                 checkMiniProductionRect2(outpostUserNameBuf, outpostNameBuf);
                 dest.bltLookup(miniProductionRect, Palette::darkGray256.getColorArray());
-                dest.bltString(pos.x, pos.y, outpostUserNameBuf, Color::cyan);
+                dest.bltString(pos.x, pos.y, outpostUserNameBuf.c_str(), Color::cyan);
```
Comment (winrid) [inline src/NetPanzer/Views/Game/VehicleSelectionView.cpp:626]: might be worth calling c_str() once and reusing the result?

File: src/NetPanzer/Views/Game/VehicleSelectionView.cpp [hunk 6]
```diff
@@ -590,11 +590,11 @@ void VehicleSelectionView::drawMiniProductionStatus(Surface &dest)
             {
                 strncpy(strBuf, obj->occupying_player->getName().c_str() , 17);
```
Comment (winrid) [inline src/NetPanzer/Views/Game/VehicleSelectionView.cpp:591]: so basically this is a mechanism to trim the player's name. If we switch this over to cpp strings we can just use the built in trim() method instead of maintaining more buffers etc, I suspect it would get optimized better, too. Probably out of scope for this PR though.

Comment (andy5995) [reply src/NetPanzer/Views/Game/VehicleSelectionView.cpp]: I tried using what I found for the built-in trim method but was told it's out of scope. I temporarily created a truncate function.

Comment (andy5995) [reply src/NetPanzer/Views/Game/VehicleSelectionView.cpp]: nvm I got rid of the truncate function

**Review by winrid — APPROVED** [review]
